image: registry.gitlab.com/kitsune_other/kitsune_docker_unittest:0.1.2

build:
  script:
    - echo Working on branch $CI_COMMIT_REF_NAME

    - ssh-keyscan -H 10.0.3.120 >> ~/.ssh/known_hosts

    - apt-get update
    - apt-get install -y libboost-filesystem-dev openssl libssl-dev  libboost-filesystem-dev libsqlite3-dev

    - cd /builds/kitsune_chan/KyoukoMind
    - ./build.sh

    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:'/builds/kitsune_chan/result'

  tags:
    - docker
