image: registry.gitlab.com/kitsune_other/kitsune_docker_unittest:0.1.0

build:
  script:
    - echo Working on branch $CI_COMMIT_REF_NAME
    - mkdir /builds/build

    - ssh-keyscan -H 10.0.3.10 >> ~/.ssh/known_hosts

    - git clone --branch 0.3.0 git@gitlab.com:kitsune_libs/libKitsuneCommon.git /builds/kitsune_chan/libKitsuneCommon

    - cd /builds/build
    - mkdir libKitsuneCommon
    - cd libKitsuneCommon
    - /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /builds/kitsune_chan/libKitsuneCommon/libKitsuneCommon.pro -spec linux-g++
    - /usr/bin/make

    - git clone --branch 0.2.1 git@gitlab.com:kitsune_libs/libKitsuneNetwork.git /builds/kitsune_chan/libKitsuneNetwork

    - cd /builds/build
    - mkdir libKitsuneNetwork
    - cd libKitsuneNetwork
    - /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /builds/kitsune_chan/libKitsuneNetwork/libKitsuneNetwork.pro -spec linux-g++
    - /usr/bin/make

    - git clone --branch 0.3.0 git@gitlab.com:kitsune_libs/libKitsuneJson.git /builds/kitsune_chan/libKitsuneJson

    - cd /builds/build
    - mkdir libKitsuneJson
    - cd libKitsuneJson
    - /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /builds/kitsune_chan/libKitsuneJson/libKitsuneJson.pro -spec linux-g++
    - /usr/bin/make



    - git clone --branch 0.1.0 git@10.0.3.10:kitsune_chan/libKitsuneChanCommon.git /builds/kitsune_chan/libKitsuneChanCommon

    - cd /builds/build
    - mkdir libKitsuneChanCommon
    - cd libKitsuneChanCommon
    - /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /builds/kitsune_chan/libKitsuneChanCommon/libKitsuneChanCommon.pro -spec linux-g++
    - /usr/bin/make



    - cd /builds/build
    - mkdir KyoukoMind
    - cd KyoukoMind
    - /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /builds/kitsune_chan/KyoukoMind/KyoukoMind.pro -spec linux-g++ "QMAKE_CXXFLAGS += -DRUN_UNIT_TEST"
    - /usr/bin/make

    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:'/builds/build/libKitsuneCommon/src'
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:'/builds/build/libKitsuneNetwork/src'
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:'/builds/build/libKitsuneJson/src'
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:'/builds/build/libKitsuneChanCommon'
    - ./KyoukoMind

  tags:
    - docker
